// cfg/layers/mids/pdhd/variants/nominal.jsonnet
//
// BASE ("nominal") variant parameter object for *pdhd* (ProtoDUNE-HD).
// Yields an object of the schema expected throughout cfg/layers/mids/pdhd/.
//
// PDHD is an HD (wrapped-APA) detector very similar to PDSP, so this reuses the
// PDSP mid api/ code and differs only in these parameters (and geometry /
// sp-filters).  Values follow the dunereco pdhd / pgrapher pdhd params.
//
// To make a new variant, do NOT edit this file: start an empty
// variants/<name>.jsonnet, import this, and override.

local wc = import "wirecell.jsonnet";
local base_variants = import "../../base/variants.jsonnet";

base_variants.nominal {

    lar: super.lar {
        // Electron lifetime.
        lifetime: 35.0 * wc.ms,
        // Electron drift speed at the PDHD field.
        drift_speed: 1.565 * wc.mm / wc.us,
    },

    geometry_data: import "geometry.jsonnet",

    binning: {
        tick: 0.5 * wc.us,
        nticks: 6000,
    },

    // Electronics response.
    elec: {
        type: "cold",
        // FE amplifier gain.
        gain: 14.0 * wc.mV / wc.fC,
        // Shaping (peaking) time.
        shaping: 2.2 * wc.us,
        // Relative gain after shaping, before ADC.
        postgain: 1.0,
    },

    // "RC" response.
    rc: {
        width: 1.1 * wc.ms,
    },

    // Digitization.  PDHD is a 14-bit ADC (contrast PDSP 12-bit).
    digi: {
        gain: 1.0,
        // Per-plane (U,V,W) voltage baselines.
        baselines: [1003.4 * wc.millivolt, 1003.4 * wc.millivolt, 507.7 * wc.millivolt],
        resolution: 14,
        fullscale: [0.2 * wc.volt, 1.6 * wc.volt],
    },

}
