// PDHD "ssss"-style variants, including the spdir_{lo,hi}fr variants used by
// test/scripts/spdir.  The <detector>-fields-{lo,hi}.json.bz2 files are
// generated by the spdir workflow (wirecell-resp condition / frzero).

local nominal = import "nominal.jsonnet";

local smeared = nominal + {
    splat: super.splat + {
        // Extra spread matching what sigproc induces (wirecell-gen morse-*).
        // Same values as PDSP; refine with a PDHD morse run if needed.
        smear_long: [
            2.691862363980221,
            2.6750200122535057,
            2.7137567141154055,
        ],
        smear_tran: [
            0.7377218875719689,
            0.7157764520393882,
            0.13980698710556544,
        ],
    },
};

{
    // Used by the morse workflow (test/scripts/morse) to measure DepoFluxSplat
    // additional smearing.  No extra smear -> the method measures it.
    morse_nominal: nominal,

    // Used by test/scripts/spdir metric (no generated FR).
    spdir: nominal,

    // Used by test/scripts/spdir.  Note, these FR files are generated.
    spdir_lofr: smeared {
        detector_data: super.detector_data {
            field: "pdhd-fields-lo.json.bz2",
        },
    },
    spdir_hifr: smeared {
        detector_data: super.detector_data {
            field: "pdhd-fields-hi.json.bz2",
        },
    },
}
