// PDVD "ssss"-style variants, including the spdir_{lo,hi}fr variants used by
// test/scripts/spdir.  The pdvd-fields-{lo,hi}.json.bz2 files are generated by
// the spdir workflow (wirecell-resp condition / frzero).

local nominal = import "nominal.jsonnet";

local smeared = nominal + {
    splat: super.splat + {
        // Placeholder extra-spread values (no PDVD morse run exists yet);
        // reuse the PDSP/PDHD numbers.  FIXME: run wirecell-gen morse-* for PDVD.
        smear_long: [
            2.691862363980221,
            2.6750200122535057,
            2.7137567141154055,
        ],
        smear_tran: [
            0.7377218875719689,
            0.7157764520393882,
            0.13980698710556544,
        ],
    },
};

{
    spdir: nominal,

    spdir_lofr: smeared {
        detector_data: super.detector_data {
            field: "pdvd-fields-lo.json.bz2",
        },
    },
    spdir_hifr: smeared {
        detector_data: super.detector_data {
            field: "pdvd-fields-hi.json.bz2",
        },
    },
}
