#+title The dnnroi training job

This job consumes "depo" files and produces "truth" and "fodder" files for use
in training DNNROI.

- depo :: file of depo sets in "WCT depo file format".
- truth :: the "depo flux splat" charge distribution represents "true" signals.
- fodder :: 3 layered image with "looseLF" filtered decon and mp2 and mp3 

* Basic command

To generate training files for DNNROI, find some depos file and run:

#+begin_example
$ wire-cell -l stderr -L debug -c spng/cfg/spng/dnnroi-training.jsonnet -A input=test/data/muon-depos.npz
#+end_example

** Options

The =dnnroi-training.jsonnet= takes several options (top-level arguments) most with defaults that control algorithms, logging and saving of intermediate tensors.

*** I/O Files

- =input= :: A "depo file", required
- ~outpat="dnnroi-training-%(tier)s.npz"~ :: file name pattern.  The tier is replaced by "truth" (true ROIs) or "fodder" (looseLF, mp2, mp3) tensor.

*** Detector context

This config creates exactly one APA.  Depos must be in this APA to be processed.
You can control which one to focus on with:

- ~tpcid=3~ :: the APA number

*** Parameters

These are some parameters exposed as TLAs with their default value

- ~rebin=4~ :: After SP filters, the data is oversampled by about a factor of 4.
  We downsample to reduce data size.  Larger than 4 downsampling can be applied
  but will begin to lose info.

- ~scale=4000.0~ :: The amount to scale down (divide by) both the looseLF "fodder"
  and "splat" truth.  The value is in units of number of ionized electrons per
  channel per time slice.  The goal is to bring these "dense" array values near
  Boolean 0's and 1's.  Whatever value is chosen here likely MUST be used during
  inference.

*** Non-parameters

- thresholds :: The "truth" produced by this job is dense and continuous.  A
  threshold must be applied by DNNROI training to produce "true ROI images".
  This threshold is a hyperparameter of the training.  The range over which it
  may be optimized depends in part on the =scale= parameter used in this job.


* Debugging

The =dnnroi-training.jsonnet= job provides some debugging options and methods.

** Options

*** Verbose logging

In addition to bare =log= many nodes react to a =verbosity= integer value

#+begin_example
-A vebosity=2
#+end_example

*** Dump out intermediate tensors

To dump out intermediate tensors a set of "tier" labels are supported by adding this option

#+begin_example
-A dump=dnnroi,wiener  
#+end_example
See the =pnode_wrappers= object in =dnnroi-training.jsonnet= for full list.


** Converting =.pkl= to =.npz=

Not many tools read the =.pkl= files directly but it is possible to convert them
into to "WCT frame files".

#+begin_example
$ ./spng/test/check-decon.py tonp tensors-*.pkl
#+end_example

** Visualizing

The dumped =.pkl= files can be plotted to PDF.

#+begin_example
$ ./spng/test/check-decon.py plot-raw tensors-*.pkl
#+end_example

The package https://github.com/brettviren/teepeesee has the command =cueteepeesee= that provides interactive visualize of WCT frame files.

#+begin_example
$ cueteepeesee dnnroi-training-truth.npz
#+end_example

