#+title The spng-ssss 🐍 Snakemake workflow script

* Overview

The [[file:../test/spng-ssss][spng-ssss]] file provides a Snakemake workflow script that will exercise
various pipelines involving SPNG.  The weird name is historical and somewhat
silly standing for simple sim sig smeared splat something something.  That it is
now in the form of a Snakemake file is extra fitting/silly.

* Getting started

#+begin_example
$ ./spng/test/spng-ssss help
Main Entry Points (Suggested Commands):
  ...
Rule Output Patterns:
  ...
#+end_example

You can replace =help= with a concrete output target file path or one of the =all_*=
targets to get some hard-wired output target file path expansions.

* Structure of workflow output

All output targets follow a common file path naming scheme under the output directory.

#+begin_example
{det}/{kind}/{tier}/{unit}/{nevent}/*
#+end_example

- det :: the name of a supported detector (fixme: so far just "pdhd")
- kind :: a high-level context name describing what is produced.
  - *line* uses ideal line segments
  - *track* uses cosmic muon simulation 
- tier :: defines the nature of the file content.  Not all content is provided for all *kind*.
  - Some tiers: kine, step, depo, splat, adc, osp, spng, fodder
- unit :: further categorizes the nature of the file content.  It's syntax depends on kind
  - ={seed}= is the unit for most output from *track* kind but *fodder* holds dnnroi training files.
  - =p{plane}-txz{xzangle}-ty{yangle}= is the unit for most *line* kind and is a per track angle and wire plane label but *summary* holds results from a fold over the tracks.
- nevent :: is the number of "events" in the output files.  This matters only for *track* kind as *line* kind is hard-wired to have one "event" (line) per file.  For *line* it is best to use ~nevent=1~ to avoid confusion.


The leaf files take general names.  You can find these:

- =data.{root,npz}= gives the primary product for most leaves.
- =training-{truth,fodder}.hdf= is special case for the *fodder* tier of *track*.
- ={lar,wct}.log= are log files from larsoft / wire-cell jobs.
- =metrics.{pdf,json}= give per-line and summary SPDIR metric data and plots.


The =spng-ssss= workflow implements these basic sub-DAGs which we can label:

- cosmics :: fills *track* kind with files related to cosmic simulation.
- training :: fills *track* kind with files for training DNNROI.
- spdir :: fills *line* kind with files for SPDIR.


* Configuration

There are two types of configuration parameters:

- implicit :: scalar values to set underlying parameters such as *device* and *container*.

- expansion :: list values over which expansion in =all_*= rules such as det, seeds, nevent, plane, line angles.  

Implicit parameters are not reflected in file path names. However, they are
saved to a =config.txt= file so changing them will lead to rules being rerun.

Changing expansion parameters should not (fixme: check) cause rule rerunning.  A
novel expansion may reuse existing upstream results.

** Container

The default container is loaded from CVMFS and each larsoft job will do a
lengthy UPS source/setup.  You can bake these into a local container for some
speed up and provide that container with, eg:

#+begin_example
--config container=/nfs/data/1/calcuttj/dunesw.sif
#+end_example

* TODO:

- [ ] Add PDVD support.  Mostly requires work in =spng/cfg/spng/detconfs/=
- [ ] Extend the "training" subgraph to include running =wcpy dnn= to train DNNROI and have the resulting model be an input to "cosmics" and "spdir" subgraphs.  This dependency should be added in a Snakemake "branch" that first tries to download the named model, eg from huggingface, before attempting to run training.
- [ ] Extend the "cosmics" subgraph to include more metrics and plots.  To start, the "spdir" per-event =metrics.json= files can be used to plot distributions of eff/bias/res.  These plots should be added to `wcpy`. 

