#!/usr/bin/env -S snakemake  --software-deployment-method apptainer --apptainer-args=" -B /cvmfs,/home,/nfs,/opt,/run/user,/etc/hostname,/etc/hosts,/etc/krb5.conf --ipc --pid" --cores all --snakefile
# -*- snakemake -*-

import os 
import numpy as np
SRC_DIR = workflow.basedir

config.setdefault('nevents', '2')
config.setdefault('detname', 'pdhd')
# container="/nfs/data/1/calcuttj/dunesw.sif"
all_theta_xz_deg=( 0,  1,  3,  5, 10, 20, 30, 45, 60, 75, 80, 82, 84, 89 )
all_planes = [0,1,2]

def same_thetaxz_plane_norm(txz, tyy):
    import numpy as np
    txz = txz*np.pi/180.
    tyy = tyy*np.pi/180.
    ret = np.array([1.,0.,0.])
    Ry = np.array([
        [np.cos(txz), 0, np.sin(txz)],
        [0.,1.,0.],
        [-np.sin(txz), 0, np.cos(txz)],
    ])
    Rx =  np.array([
        [1., 0., 0.],
        [0., np.cos(tyy), np.sin(tyy)],
        [0., -np.sin(tyy), np.cos(tyy)]
    ])

    return Rx @ (Ry @ ret)

def xz_y_from_samexz(v):
    import numpy as np
    y = np.acos(v[1])
    xz = np.asin(v[0]/np.sin(y))
    xz = xz*180./np.pi
    y = y*180./np.pi
    # print(f'{xzu},{xzv} --> {xz:.2f}, {y:.2f}') 
    return xz, y

def xz_y_from_xzw_xzu(xzw, xzu, tyy=35.7):
    import numpy as np
    vw = same_thetaxz_plane_norm(xzw, 0)
    vu = same_thetaxz_plane_norm(xzu, tyy)
    v = np.linalg.cross(vu, vw)
    v /= np.linalg.norm(v)
    xz, y = xz_y_from_samexz(v)
    print(f'{xzw},{xzu} --> {xz:.2f}, {y:.2f}') 
    return xz, y

def xz_y_from_xzu_xzv_hyu(xzu, xzv, tyy=-35.7):
    import numpy as np
    vu = same_thetaxz_plane_norm(xzu, tyy)
    vv = same_thetaxz_plane_norm(xzv, -tyy)
    v = np.linalg.cross(vv, vu)
    v /= np.linalg.norm(v)

    xz, y = xz_y_from_samexz(v)
    print(f'{xzu},{xzv} --> {xz:.2f}, {y:.2f}') 
    return xz, y 

high_end_xzu_xzv_deg=([75, 75], [80, 80], [82,82], [85,85], [75, 87], [85, 87], [87, 75], [87, 85], [87, 87])
high_end_xzu_xzv_deg_uplane=([75, 75], [80, 80], [82,82], [85,85], [87, 75], [87, 85], [87, 87])
high_end_xzw_xzu_deg_wplane=([75, 75], [80, 80], [82,82], [85,85], [87, 75], [87, 85], [87, 87])
high_end_xzu_xzv_deg_vplane=([75, 75], [80, 80], [82,82], [85,85], [75, 87], [85, 87], [87, 87])

def resolve_angles(w):
    if w.plane in ['u', 'v']:
        conversion = xz_y_from_xzu_xzv_hyu
    elif w.plane == 'w':
        conversion = xz_y_from_xzw_xzu
    return conversion(float(w.t1), float(w.t2))

rule linedepos_xzu_xzv:
    output:
        depos='linedepos-pdhd-{plane}plane-t1_{t1}-t2_{t2}_wct-depos.npz',
        meta='linedepos-pdhd-{plane}plane-t1_{t1}-t2_{t2}_wct-depos.json',
    params:
        offset="--offset '1*m,0*m,0*m'",
        xz_y = resolve_angles
        
    shell: '''

    wcpy gen detlinegen \
    {params.offset} \
    --detector=pdhd \
    --plane=0 \
    --angle-coords=global \
    --theta_xz="{params.xz_y[0]}*deg" \
    --theta_y="{params.xz_y[1]}*deg" \
    --output_depos {output.depos} \
    --output_meta {output.meta}
    '''


rule test_container:
    container:
        "/nfs/data/1/calcuttj/dunesw.sif"
    output:
        'lartest.txt'
    shell:
        """
        lar -h > {output}
        """
rule lar_version:
    container:
        "/cvmfs/singularity.opensciencegrid.org/fermilab/fnal-dev-sl7:latest"
    output:
        "version.txt"
    input:
        os.path.join(SRC_DIR, "run_larsoft.sh")
    shell: """
    {input} --version > {output} 2>&1
    """

rule gen_cosmics:
    #TODO ADD CONFIGURATION FOR NUMBER OF EVENTS
    container:
        # "/cvmfs/singularity.opensciencegrid.org/fermilab/fnal-dev-sl7:latest"
        "/nfs/data/1/calcuttj/dunesw.sif"
    output:
        "cosmics_{sample}_gen.root"
    shell:
        """
        # set +euo pipefail  # Disable Snakemake's strict mode Yay UPS
        # source /cvmfs/dune.opensciencegrid.org/products/dune/setup_dune.sh
        # setup dunesw v10_14_00d00 -q e26:prof
        # set -euo pipefail  # Reenable Snakemake's strict mode

        lar --no-timing --no-memcheck -n {config[nevents]} -c prod_cosmics_protodunehd.fcl -o {output} -T hist_{output}
        rm hist_{output}
        """

rule g4:
    container:
        # "/cvmfs/singularity.opensciencegrid.org/fermilab/fnal-dev-sl7:latest"
        "/nfs/data/1/calcuttj/dunesw.sif"
    input:
        file="cosmics_{sample}_gen.root",
        fcl=os.path.join(SRC_DIR, "run_g4_only.fcl"),
    output:
        temp("cosmics_{sample}_g4.root")
    shadow: "minimal"
    shell:
        """
        # set +euo pipefail  # Disable Snakemake's strict mode Yay UPS
        # source /cvmfs/dune.opensciencegrid.org/products/dune/setup_dune.sh
        # setup dunesw v10_14_00d00 -q e26:prof
        # set -euo pipefail  # Reenable Snakemake's strict mode

        lar --no-timing --no-memcheck -c {input.fcl} {input.file} -o {output} -T hist_{output}
        rm hist_{output} #No need to save these
        """

rule save_depos:
    container:
        # "/cvmfs/singularity.opensciencegrid.org/fermilab/fnal-dev-sl7:latest"
        "/nfs/data/1/calcuttj/dunesw.sif"
    input:
        inputfile="cosmics_{sample}_g4.root",
        fcl=os.path.join(SRC_DIR, "pdhd_wirecell_save_depos.fcl"),
        js=os.path.join(SRC_DIR, "wcls-save-larg4-depos.jsonnet"),
    output:
        npz="cosmics_{sample}_wct-depos.npz",
        # bz2='{name}_wct-depos.tar.bz2'
    shadow: "minimal" #This runs in an auto-removed tmp dir
    shell:
        """
        # set +euo pipefail  # Disable Snakemake's strict mode Yay UPS
        # source /cvmfs/dune.opensciencegrid.org/products/dune/setup_dune.sh
        # setup dunesw v10_14_00d00 -q e26:prof
        # set -euo pipefail  # Reenable Snakemake's strict mode

        export WIRECELL_PATH={SRC_DIR}:$WIRECELL_PATH

        lar --no-timing --no-memcheck -c {input.fcl} {input.inputfile} --no-output
        # ls *tar.bz2
        mv wct-depos.npz {output.npz}
        # mv wct-depos.tar.bz2 
        """


config.setdefault('tpcid', '0')
config.setdefault('device', 'cpu')
config.setdefault('mpsigproc_training_js', 'dnnroi-training.jsonnet')
rule spng_mpsigproc:
    input:
        "cosmics_{sample}_wct-depos.npz",
    envmodules:
      "wire-cell-toolkit/spng-gcc-11.5.0-fk4b2v4"
    output:
        "sigproc-spng-mp-cosmics_{sample}.tar"
    params:
        # jsonnet='dnnroi-training.jsonnet',
        jsonnet=config['mpsigproc_training_js'],
        tpcid=config['tpcid'],
        detname=config['detname'],
        device=config['device']
    shadow: "minimal"
    shell:
        """
        #export WIRECELL_PATH=/lbne/u/jcalcutt/wire-cell-toolkit/spng/:/lbne/u/jcalcutt/wire-cell-toolkit/spng/cfg:/lbne/u/jcalcutt/wire-cell-data:${{WIRECELL_PATH}}
        wire-cell -l stdout -L debug cfg/spng/{params.jsonnet} -A "input={input}" \
            -A "tpcid={params.tpcid}" -A "detname={params.detname}" --tla-code "crossed_views=[1,1,1]" \
            -A "device={params.device}"
        # tar the output files
        tar -cf {output} dnnroi-training-truth.npz \
        dnnroi-training-fodder.npz
        """

use rule spng_mpsigproc as spng_mpsigproc_target with:
    input:
        "target-{target}_{sample}_wct-depos.npz"
    output:
        "sigproc-spng-mp-target-{target}_{sample}.tar"

rule spng_mpsigproc_lines:
    resources:
        gpu = 1 if config['device'] == 'gpu' else 0
    input:
        'linedepos-pdhd-{plane}plane-t1_{t1}-t2_{t2}_wct-depos.npz'
    output:
        "sigproc-spng-mp-linedepos-pdhd-{plane}plane-t1_{t1}-t2_{t2}.tar"
    params:
        jsonnet=config['mpsigproc_training_js'],
        tpcid=config['tpcid'],
        detname=config['detname'],
        device=config['device'],
    shadow: "minimal"
    envmodules:
      "wire-cell-toolkit/spng-gcc-11.5.0-fk4b2v4"
    shell:
        """
        wire-cell -l stdout -L debug cfg/spng/{params.jsonnet} -A "input={input}" \
            -A "tpcid={params.tpcid}" -A "detname={params.detname}" --tla-code "crossed_views=[1,1,1]" \
            -A "device={params.device}"
        # tar the output files
        tar -cf {output} dnnroi-training-truth.npz \
        dnnroi-training-fodder.npz
        """


config.setdefault('external_loc', '')

rule spng_densesigproc:
    input:
        #TODO Remove external loc
        os.path.join(config['external_loc'], "cosmics_{sample}_wct-depos.npz"),
    output:
        temp("sigproc-spng-dense-cosmics_{sample}.tar")
        # "sigproc-spng-dense-{name}.tar"
    shadow: "minimal"
    params:
        jsonnet='dnnroi-training-dense-only.jsonnet',
        detname=config['detname'],
    shell:
        """
        wire-cell -l stdout -L debug {params.jsonnet} -A "input={input}" \
            -A "tpcid=0" -A "detname={params.detname}"
        # tar the output files
        tar -cf {output} dnnroi-training-truth.npz \
        dnnroi-training-fodder.npz
        """

rule spng_densesigproc_lines:
    input:
        #TODO Remove external loc
        os.path.join(config['external_loc'], 'linedepos-pdhd-{plane}plane-t1_{t1}-t2_{t2}_wct-depos.npz'),
    output:
        "sigproc-spng-dense-linedepos-pdhd-{plane}plane-t1_{t1}-t2_{t2}.tar"
    shadow: "minimal"
    params:
        jsonnet='dnnroi-training-dense-only.jsonnet',
        detname=config['detname'],
    shell:
        """
        wire-cell -l stdout -L debug {params.jsonnet} -A "input={input}" \
            -A "tpcid=0" -A "detname={params.detname}"
        # tar the output files
        tar -cf {output} dnnroi-training-truth.npz \
        dnnroi-training-fodder.npz
        """

## For more flexibility, create a separate rule to unpack into hdf5 for each plane
for i in range(3):
    rule:
        name: f'convert_spng_mp_to_hdf5_{i}'
        input:
            "sigproc-spng-mp-cosmics_{sample}.tar"
        output:
            **{
                f'rec{i}':f'cosmics_{{sample}}-g4-rec-{i}.h5',
                f'tru{i}':f'cosmics_{{sample}}-g4-tru-{i}.h5',
            }
        script:
            "scripts/convert_to_h5mpSnake.py"
    rule:
        name: f'convert_spng_mp_to_hdf5_lines_{i}'
        input:
            "sigproc-spng-mp-linedepos-pdhd-{plane}plane-t1_{t1}-t2_{t2}.tar"
        output:
            **{
                f'rec{i}':'linedepos-pdhd-{plane}plane-t1_{t1}-t2_{t2}-g4-rec-'+f'{i}.h5',
                f'tru{i}':'linedepos-pdhd-{plane}plane-t1_{t1}-t2_{t2}-g4-tru-'+f'{i}.h5',
            }
        script:
            "scripts/convert_to_h5mpSnake.py"
    rule:
        name: f'convert_spng_mp_to_hdf5_target_{i}'
        input:
            "sigproc-spng-mp-target-{target}_{sample}.tar"
        output:
            **{
                f'rec{i}':f'target-{{target}}_{{sample}}-g4-rec-{i}.h5',
                f'tru{i}':f'target-{{target}}_{{sample}}-g4-tru-{i}.h5',
            }
        script:
            "scripts/convert_to_h5mpSnake.py"
    

# seeds = []
# import random
# config.setdefault('nseeds', 1)
# for i in range(int(config['nseeds'])):

#     these_seeds = '.'.join([str(random.randint(0,100)) for j in range(5)])
#     seeds.append(these_seeds)

rule high_end_mp_hdf5:
    input:
        rec0 = [expand("linedepos-pdhd-{plane}plane" +f"-t1_{t1}-t2_{t2}-g4-rec-0.h5", plane=['u', 'v', 'w']) for t1, t2 in high_end_xzu_xzv_deg],
        tru0 = [expand("linedepos-pdhd-{plane}plane" +f"-t1_{t1}-t2_{t2}-g4-tru-0.h5", plane=['u', 'v', 'w']) for t1, t2 in high_end_xzu_xzv_deg],
        rec1 = [expand("linedepos-pdhd-{plane}plane" +f"-t1_{t1}-t2_{t2}-g4-rec-1.h5", plane=['u', 'v', 'w']) for t1, t2 in high_end_xzu_xzv_deg],
        tru1 = [expand("linedepos-pdhd-{plane}plane" +f"-t1_{t1}-t2_{t2}-g4-tru-1.h5", plane=['u', 'v', 'w']) for t1, t2 in high_end_xzu_xzv_deg],
        rec2 = [expand("linedepos-pdhd-{plane}plane" +f"-t1_{t1}-t2_{t2}-g4-rec-2.h5", plane=['u', 'v', 'w']) for t1, t2 in high_end_xzu_xzv_deg],
        tru2 = [expand("linedepos-pdhd-{plane}plane" +f"-t1_{t1}-t2_{t2}-g4-tru-2.h5", plane=['u', 'v', 'w']) for t1, t2 in high_end_xzu_xzv_deg],




## TODO 
rule convert_spng_dense_to_hdf5:
    input:
        "sigproc-spng-dense-cosmics_{sample}.tar"
    output:
        rec="cosmics_{sample}-g4-rec-dense-0.h5",
        tru="cosmics_{sample}-g4-tru-dense-0.h5",
    script:
        "scripts/convert_to_h5denseSnake.py"
# rule convert_spng_dense_to_hdf5_lines:
#     input:
#         "seeds_{seeds}/sigproc-spng-dense-linedepos-pdhd-plane0-txzu{xzu}-txzv{xzv}.tar"
#     output:
#         rec="seeds_{seeds}/linedepos-pdhd-plane0-txzu{xzu}-txzv{xzv}-g4-rec-dense-0.h5",
#         tru="seeds_{seeds}/linedepos-pdhd-plane0-txzu{xzu}-txzv{xzv}-g4-tru-dense-0.h5",
#     script:
#         "scripts/convert_to_h5denseSnake.py"

# rule high_end_dense_hdf5_seeded:
#     input:
#         rec = [expand("seeds_{seeds}" + f"/linedepos-pdhd-plane0-txzu{xzu}-txzv{xzv}-g4-rec-dense-0.h5", seeds=seeds) for xzu, xzv in high_end_xzu_xzv_deg],
#         tru = [expand("seeds_{seeds}" + f"/linedepos-pdhd-plane0-txzu{xzu}-txzv{xzv}-g4-tru-dense-0.h5", seeds=seeds) for xzu, xzv in high_end_xzu_xzv_deg]


config.setdefault('test_input', 'blah')
config.setdefault('test_tpcs', [0])

def run_plot(angles):
    import torch
    import matplotlib.pyplot as plt
    import numpy as np
    all_effs = []
    all_purs = []

    xlabels = [f'{u},{v}' for u,v in angles]
    xpos = [i for i in range(len(xlabels))]

    ranges = [[0,800], [800,1600], [1600,2560]]
    for f in input:
        t = torch.load(f)
        labels = t['labels'][0].detach().cpu()
        y = t['y'][0].detach().cpu()

        for plane in params.test_tpcs:
            this_range = ranges[plane]
            real_pixels = torch.where(labels[this_range[0]:this_range[1]] > 0)
            eff = (y[this_range[0]:this_range[1]][real_pixels] > .5).sum()/labels[this_range[0]:this_range[1]].sum()
            all_effs.append(eff)

            pur = (y[this_range[0]:this_range[1]][real_pixels] > .5).sum()/(y[this_range[0]:this_range[1]] > .5).sum()
            all_purs.append(pur)
    print(all_effs)
    print(all_purs)

    plt.subplot(2, 1, 1)
    plt.plot(all_effs, label='Efficiency')
    plt.xticks(xpos, xlabels)
    plt.grid(True, axis='both')
    plt.ylim(0., 1.5)
    plt.subplot(2, 1, 2)
    plt.plot(all_purs)
    plt.grid(True, axis='both')
    plt.yticks(np.arange(0.,1.5, .2))
    plt.xticks(xpos, xlabels, label='Purity')
    plt.ylim(0., 1.5)
    plt.yticks(np.arange(0.,1.5, .2))
    f = output[0]
    print(type(f))
    print(f)
    plt.savefig(f)

import os
def get_angles_by_plane(plane):
    if plane == 'u':
        angles = high_end_xzu_xzv_deg_uplane
    elif plane == 'v':
        angles = high_end_xzu_xzv_deg_vplane
    elif plane == 'w':
        angles = high_end_xzw_xzu_deg_wplane
    else:
        raise RuntimeError(f'Unknown plane {plane}')
    return angles


#
# Run an a reco/true h5 pair through a model
#
plane_to_view = {'u':0, 'v':1, 'w':2}
config.setdefault('dnnapp', 'dnnroi_custom')
config.setdefault('model', '')
config.setdefault('cfg', '')
rule run_one:
    input:
        rec=lambda w : ('linedepos-pdhd-{plane}plane-t1_{t1}-t2_{t2}-g4-rec-' + f'{plane_to_view[w.plane]}.h5'),
        tru=lambda w : ('linedepos-pdhd-{plane}plane-t1_{t1}-t2_{t2}-g4-tru-' + f'{plane_to_view[w.plane]}.h5'),
    benchmark:
        '<benchmarks>/run_one_{t1}_{t2}_{plane}'
    output:
        '<results>/test_line_{plane}plane_t1-{t1}-t2-{t2}.pt'
    params:
        device=config['device'],
        model=config['model'],
        app=config['dnnapp'],
        cfg=config['cfg'],
    resources:
        gpu = 1 if config['device'] == 'gpu' else 0
    shell: """
    wcpy dnn run_one \
    {input.rec} {input.tru} \
    --app {params.app} \
    -l {params.model} \
    -c {params.cfg} \
    --manual-sigmoid \
    -d {params.device} \
    -o {output}
    """

config.setdefault('cpt_dir', '.')
config.setdefault('proc', '0')
config.setdefault('cluster', '0')
use rule run_one as run_one_epoch with:
    pathvars:
      results="epoch_{epoch}",
      benchmarks="epoch_benchmarks_{epoch}"
    params:
      model=f'{config["cpt_dir"]}/checkpoint_{config["proc"]}_{config["cluster"]}_{{epoch}}.pt'

use rule run_one as run_one_xvu with:
    input:
        rec=[f'linedepos-pdhd-{{plane}}plane-t1_{{t1}}-t2_{{t2}}-g4-rec-{i}.h5' for i in range(3)],
        tru=[f'linedepos-pdhd-{{plane}}plane-t1_{{t1}}-t2_{{t2}}-g4-tru-{i}.h5' for i in range(3)],
    output:
        '<results>/xvu-test_line_{plane}plane_t1-{t1}-t2-{t2}.pt'

use rule run_one_xvu as run_one_xvu_epoch with:
    pathvars:
      results="epoch_{epoch}",
      benchmarks="epoch_benchmarks_{epoch}"
    params:
      model=f'{config["cpt_dir"]}/checkpoint_{config["proc"]}_{config["cluster"]}_{{epoch}}.pt'

def get_input_by_plane(wildcards):
    angles = get_angles_by_plane(wildcards.plane)
    return [
        f'<results>/test_line_{wildcards.plane}plane_t1-{t1}-t2-{t2}.pt' for t1,t2 in angles
    ]
def get_input_by_plane_xvu(wildcards):
    angles = get_angles_by_plane(wildcards.plane)
    return [
        f'<results>/xvu-test_line_{wildcards.plane}plane_t1-{t1}-t2-{t2}.pt' for t1,t2 in angles
    ]

rule pixel_eff_pur:
    params:
        # threshold=0.5,
        chan_range=(0, 800),
    run:
        import torch
        import numpy as np
        t = torch.load(input[0])
        labels = t['labels'][0].detach().cpu()
        y = t['y'][0].detach().cpu()
        this_range=params.chan_range
        real_pixels = torch.where(labels[this_range[0]:this_range[1]] > 0)
        threshold = float(wildcards.threshold)
        eff = (y[this_range[0]:this_range[1]][real_pixels] > threshold).sum()/labels[this_range[0]:this_range[1]].sum()
        pur = (y[this_range[0]:this_range[1]][real_pixels] > threshold).sum()/(y[this_range[0]:this_range[1]] > threshold).sum()

        np.savez(output[0], eff=eff, pur=pur)

use rule pixel_eff_pur as pixel_eff_pur_xvu_line with:
    input:
        '<results>/xvu-test_line_{plane}plane_t1-{t1}-t2-{t2}.pt'
    output:
        '<results>/xvu-test_line_{plane}plane_t1-{t1}-t2-{t2}-eff-pur-t{threshold}.npz'
    # params:
    #     threshold=wildcards.threshold

rule eff_pur_scan:
    input:
        expand('<results>/xvu-test_line_uplane_t1-75-t2-75-eff-pur-t{threshold}.npz',
               threshold=np.arange(0.05,1.0,0.05))
    output:
        '<results>/test_scan.npz'
    run:
        import numpy as np
        effs = []
        purs = []
        for inp in input:
            t = np.load(inp)
            effs.append(t['eff'])
            purs.append(t['pur'])
        np.savez(output[0], effs=effs, purs=purs)


rule plot_eff_pur:
    input:
        get_input_by_plane
    output:
        png='<results>/all_eff_pur_{plane}plane.png',
        npz='<results>/all_eff_pur_{plane}plane.npz',
    params:
        test_tpcs = [int(i) for i in config['test_tpcs']] #This is a bad name for this but oh well
    benchmark:
        '<benchmarks>/{plane}_plot_eff_pur'
    run:
        import torch
        import matplotlib.pyplot as plt
        import matplotlib
        matplotlib.use('Agg')
        import numpy as np
        all_effs = []
        all_purs = []

        xlabels = [f'{u},{v}' for u,v in get_angles_by_plane(wildcards.plane)]
        xpos = [i for i in range(len(xlabels))]

        ranges = [[0,800], [800,1600], [1600,2560]]
        for f in input:
            t = torch.load(f)
            labels = t['labels'][0].detach().cpu()
            y = t['y'][0].detach().cpu()

            for plane in params.test_tpcs:
                this_range = ranges[plane]
                real_pixels = torch.where(labels[this_range[0]:this_range[1]] > 0)
                eff = (y[this_range[0]:this_range[1]][real_pixels] > .5).sum()/labels[this_range[0]:this_range[1]].sum()
                all_effs.append(eff)

                pur = (y[this_range[0]:this_range[1]][real_pixels] > .5).sum()/(y[this_range[0]:this_range[1]] > .5).sum()
                all_purs.append(pur)
        print(all_effs)
        print(all_purs)

        plt.subplot(2, 1, 1)
        plt.plot(all_effs, label='Efficiency')
        plt.xticks(xpos, xlabels)
        plt.grid(True, axis='both')
        plt.ylim(0., 1.5)
        plt.subplot(2, 1, 2)
        plt.plot(all_purs)
        plt.grid(True, axis='both')
        plt.yticks(np.arange(0.,1.5, .2))
        plt.xticks(xpos, xlabels, label='Purity')
        plt.ylim(0., 1.5)
        plt.yticks(np.arange(0.,1.5, .2))
        f = output.png
        print(type(f))
        print(f)
        plt.savefig(f)

        np.savez(output.npz, effs=all_effs, purs=all_purs)

use rule plot_eff_pur as plot_eff_pur_epoch with:
    pathvars:
        results="epoch_{epoch}",
        benchmarks="{plane}_epoch_{epoch}_plot_eff_pur_benchmarks"

use rule plot_eff_pur as plot_eff_pur_xvu with:
    input: get_input_by_plane_xvu
    output:
        png='<results>/all_eff_pur_{plane}plane-xvu.png',
        npz='<results>/all_eff_pur_{plane}plane-xvu.npz',
    params:
        test_tpcs = lambda wildcards: [plane_to_view[wildcards.plane]]

use rule plot_eff_pur_xvu as plot_eff_pur_xvu_epoch with:
    pathvars:
        results="epoch_{epoch}",
        benchmarks="{plane}_epoch_{epoch}_plot_eff_pur_benchmarks"

def get_input(wildcards):
    return f'test_line_{wildcards.plane}plane_t1-{wildcards.t1}-t2-{wildcards.t2}.pt'


rule plot_feat_y_labels:
    input:
        # 'test_line_txzu82-txzv82.pt'
        get_input
    output:
        pickle=temp('line-display-{plane}plane-t1_{t1}-t2_{t2}.pickle'),
        png='line-display-{plane}plane-t1_{t1}-t2_{t2}.png'
    run:
        import torch
        import matplotlib
        matplotlib.use('Agg')
        import matplotlib.pyplot as plt
        import warnings

        # 1. Force TrueType fonts (Type 42) instead of Type 3
        matplotlib.rcParams['pdf.fonttype'] = 42
        matplotlib.rcParams['ps.fonttype'] = 42

        # 2. Aggressively suppress the warning that triggers the crash
        # This prevents the 'warn_on_missing_glyph' function from ever running
        warnings.filterwarnings("ignore", category=UserWarning, module="matplotlib")

        # 3. Use a standard font that is widely available on Linux
        plt.rcParams['font.family'] = 'DejaVu Sans'
        t = torch.load(input[0])
        feat = t['feat']; y = t['y']; labels = t['labels']
        fig, axs = plt.subplots(3,1)
        for i, f in enumerate([feat, y >.5, labels]):
            im = axs[i].imshow(f[0].detach().cpu(), aspect='auto'); plt.colorbar(im)
        # plt.title(f'XZu:{wildcards.txzu}, XZv:{wildcards.txzv}')

        f = output.png
        plt.savefig(f)

        f = output.pickle
        # print(f)
        # plt.savefig(f)
        import pickle
        pickle.dump(fig, open(f, 'wb'))

use rule plot_feat_y_labels as plot_feat_y_labels_xvu with:
    input: '<results>/xvu-test_line_{plane}plane_t1-{t1}-t2-{t2}.pt'
    output: 
        pickle=temp('xvu-line-display-{plane}plane-t1_{t1}-t2_{t2}.pickle'),
        png='line-display-{plane}plane-t1_{t1}-t2_{t2}.png'


def get_plot_input_by_plane(w):
    if w.plane == 'u':
        angles = high_end_xzu_xzv_deg_uplane
    elif w.plane == 'v':
        angles = high_end_xzu_xzv_deg_vplane
    elif w.plane == 'w':
        angles = high_end_xzw_xzu_deg_wplane
    res = [f'line-display-{w.plane}plane-t1_{t1}-t2_{t2}.pickle' for t1, t2 in angles]
    return res

def xvu_get_plot_input_by_plane(w):
    return ['xvu-' + r for r in get_plot_input_by_plane(w)]

rule collect_feat_y_labels_uvplane:
    input:
        get_plot_input_by_plane
    output:
        'line-displays_{plane}plane.tar'
    shell:
        'tar -cf {output} {input}'

use rule collect_feat_y_labels_uvplane as xvu_collect_feat_y_labels_uvplane with:
    input:
        xvu_get_plot_input_by_plane
    output:
        'xvu-line-displays_{plane}plane.tar'

rule all_plots_u:
    input:
        tar=f'line-displays_uplane.tar',
        effpur=f'all_eff_pur_uplane.png',
        npy=f'all_eff_pur_uplane.npz',
rule all_plots_v:
    input:
        tar=f'line-displays_vplane.tar',
        effpur=f'all_eff_pur_vplane.png',
        npy=f'all_eff_pur_vplane.npz',
rule all_plots_w:
    input:
        tar=f'line-displays_wplane.tar',
        effpur=f'all_eff_pur_wplane.png',
        npy=f'all_eff_pur_wplane.npz',

rule all_plots_u_xvu:
    input:
        tar=f'xvu-line-displays_uplane.tar',
        effpur=f'<results>/all_eff_pur_uplane-xvu.png',
        npy=f'<results>/all_eff_pur_uplane-xvu.npz',
rule all_plots_v_xvu:
    input:
        tar=f'xvu-line-displays_vplane.tar',
        effpur=f'<results>/all_eff_pur_vplane-xvu.png',
        npy=f'<results>/all_eff_pur_vplane-xvu.npz',
rule all_plots_w_xvu:
    input:
        tar=f'xvu-line-displays_wplane.tar',
        effpur=f'<results>/all_eff_pur_wplane-xvu.png',
        npy=f'<results>/all_eff_pur_wplane-xvu.npz',

rule all_eff_pur_xvu:
    input:
        '<results>/all_eff_pur_uplane-xvu.npz',
        '<results>/all_eff_pur_vplane-xvu.npz',
        '<results>/all_eff_pur_wplane-xvu.npz',


def glob_epochs(w):
    from glob import glob
    # epoch_dirs = list(set(glob("epoch_**/")) - set(glob("epoch_benchmarks_**/")))
    cpts = glob(f'{config["cpt_dir"]}/checkpoint*.pt')
    #return [f'epoch_{d}/all_eff_pur_{p}plane-xvu.npz' for d in range(len(cpts)) for p in ('u', 'v', 'w')]
    #ASSUMES EPOCH NUMBER IS LAST IN STRING AND AFTER _
    return [f'epoch_{cpt.replace(".pt","").split('_')[-1]}/all_eff_pur_{p}plane-xvu.npz' for cpt in cpts for p in ('u', 'v', 'w')]

rule all_epochs_xvu:
    input: glob_epochs
        

#rule run_checkpoints:
#    input:
#    	f'{config["cpt_dir"]}/checkpoint_0_0_{{epoch}}.pt'
#    output:
#        'epoch_{epoch}/blah.txt'
#    shell:
#        '''
#        echo blah > {output}
#	'''

def get_epochs(wildcards):
    from glob import glob
    return sorted(
        glob(f'epoch_*/all_eff_pur_{wildcards.plane}plane.npz'),
        key = lambda s : int(s.split('/')[0].split('_')[-1])
    )

def get_epochs_xvu(wildcards):
    from glob import glob
    return sorted(
        glob(f'epoch_*/all_eff_pur_{wildcards.plane}plane-xvu.npz'),
        key = lambda s : int(s.split('/')[0].split('_')[-1])
    )

rule compare_effpur_epochs:
    input: get_epochs
    output:
        pdf='<results>/eff_pur_epochs_{plane}plane.pdf',
        # npz='eff_pur_epochs_{plane}plane.npz',
    run:
        print(input)
        import numpy as np, matplotlib.pyplot as plt
        import matplotlib
        matplotlib.use('Agg')
        matplotlib.rcParams['pdf.fonttype'] = 42
        files = [np.load(f) for f in input]
        epoch_nums = [int(f.split('/')[0].split('_')[-1]) for f in input]
        n_angles = len(files[0]['effs'])
        n_epochs = len(files)
        effs = np.array([
            [f['effs'][i] for f in files]
            for i in range(n_angles)
        ])
        purs = np.array([
            [f['purs'][i] for f in files]
            for i in range(n_angles)
        ])

        from matplotlib.backends.backend_pdf import PdfPages
        with PdfPages(output.pdf) as pdf:
            for i in range(len(effs)):
                plt.figure()
                plt.plot(epoch_nums, effs[i], label='Efficiency')
                plt.plot(epoch_nums, purs[i], label='Purity')
                plt.plot(epoch_nums, effs[i]*purs[i], label='eff x pur')
                plt.ylim(0,1.2)
                plt.grid(True, axis='both')
                plt.title(f'Angle #{i}')
                plt.xlabel('Epoch')
                plt.legend()
                pdf.savefig()
                plt.close()
            plt.figure()
            plt.title('Efficiency -- all epochs')
            plt.xlabel('Angle')
            plt.ylim(0,1.2)
            plt.ylabel('Efficiency')
            plt.grid(True, axis='both')
            for i, eff in enumerate(effs.T):
                plt.plot(eff, label=f'Epoch {epoch_nums[i]}')
            pdf.savefig()
            plt.close()

            plt.figure()
            plt.title('Purity -- all epochs')
            plt.xlabel('Angle')
            plt.ylim(0,1.2)
            plt.ylabel('Purity')
            plt.grid(True, axis='both')
            for i, pur in enumerate(purs.T):
                plt.plot(pur, label=f'Epoch {epoch_nums[i]}')
            pdf.savefig()
            plt.close()

            plt.figure()
            plt.title('Purity -- all epochs')
            img = plt.imshow(purs, aspect='auto', interpolation='none', vmin=0.5, vmax=1.0)
            plt.xlabel('Epoch')
            plt.ylabel('Angle')
            cbar = plt.colorbar(img); cbar.ax.set_title('Purity', pad=10)
            pdf.savefig()
            plt.close()

            plt.figure()
            plt.title('Efficiency -- all epochs')
            img = plt.imshow(effs, aspect='auto', interpolation='none', vmin=0.5, vmax=1.0)
            plt.xlabel('Epoch')
            plt.ylabel('Angle')
            cbar = plt.colorbar(img); cbar.ax.set_title('Efficiency', pad=10)
            pdf.savefig()
            plt.close()

use rule compare_effpur_epochs as compare_effpur_epochs_xvu with:
    input: get_epochs_xvu
    output:
        pdf='<results>/eff_pur_epochs_{plane}plane-xvu.pdf',
