/** Mirror classes for reading SBND "reco1" art/LArSoft ROOT files with
 * bare ROOT (no LArSoft, no gallery).
 *
 * These class definitions were derived from TFile::MakeProject output on
 * data_filtered_decoded_reco1-fe6033f3-07a0-4971-cea5-16ce59269fba_eventidfiltered.root
 * (SBND 2025 fall production data, runs 18255/18306; ROOT 6.32.02) and
 * hand-trimmed to the subset needed by SBNDReco1FrameSource and
 * SBNDReco1OpFlashSource.  Member names, types and order MUST match the
 * StreamerInfo embedded in the input files -- ROOT matches file classes
 * to these in-memory classes by name and evolves by member name.
 *
 * The art ROOT layout is an exchange format we do not own; these two
 * components (plus root/dict/LinkDef.h) are the only places that know
 * about it.  See root/docs/sbnd-reco1-source.md.
 *
 * File streamer versions at generation time: recob::Wire v19,
 * recob::OpFlash v19, recob::OpHit v15, art::EventAuxiliary v12,
 * art::Wrapper v11, lar::sparse_vector<float> v1.  The ClassDef versions
 * below are the MakeProject-assigned ones (file version + 1); schema
 * evolution handles the difference.
 */
#ifndef WIRECELLROOT_SBNDRECO1PRODUCTS
#define WIRECELLROOT_SBNDRECO1PRODUCTS

#include "Rtypes.h"

#include <string>
#include <vector>

namespace lar {
    template <typename T0> class range_t;
    template <> class range_t<unsigned long> {
      public:
        unsigned long offset{0};  // offset (absolute index) of the first element
        unsigned long last{0};    // offset (absolute index) after the last element
        range_t() {}
        virtual ~range_t() {}
        ClassDef(range_t, 11);  // Generated by MakeProject.
    };

    template <typename T0> class sparse_vector;
    template <> class sparse_vector<float> {
      public:
        class datarange_t : public lar::range_t<unsigned long> {
          public:
            std::vector<float> values;  // data in the range
            datarange_t() {}
            virtual ~datarange_t() {}
            ClassDef(datarange_t, 11);  // Generated by MakeProject.
        };

        unsigned long nominal_size{0};  // current size
        std::vector<datarange_t> ranges;  // list of ranges
        sparse_vector() {}
        virtual ~sparse_vector() {}
        ClassDef(sparse_vector, 11);  // Generated by MakeProject.
    };
}  // namespace lar

namespace recob {
    class Wire {
      public:
        unsigned int fChannel{0};  // ID of the associated channel
        Int_t fView{0};            // View corresponding to the plane of this wire
        lar::sparse_vector<float> fSignalROI;  // Signal on the channel per time tick
        Wire() {}
        virtual ~Wire() {}
        ClassDef(Wire, 20);  // Generated by MakeProject.
    };

    class OpFlash {
      public:
        double fTime{0};       // Time on trigger time scale [us]
        double fTimeWidth{0};  // Width of the flash in time [us]
        double fAbsTime{0};    // Time by PMT readout clock
        unsigned int fFrame{0};  // Frame number
        std::vector<double> fPEperOpDet;   // Number of PE on each PMT
        std::vector<double> fWireCenters;  // Geometric center in each view
        std::vector<double> fWireWidths;   // Geometric width in each view
        double fXCenter{0};
        double fXWidth{0};
        double fYCenter{0};
        double fYWidth{0};
        double fZCenter{0};
        double fZWidth{0};
        double fFastToTotal{0};
        bool fInBeamFrame{false};
        int fOnBeamTime{0};
        OpFlash() {}
        virtual ~OpFlash() {}
        ClassDef(OpFlash, 20);  // Generated by MakeProject.
    };

    class OpHit {
      public:
        int fOpChannel{0};
        unsigned short fFrame{0};
        double fPeakTime{0};
        double fPeakTimeAbs{0};
        double fStartTime{0};
        double fRiseTime{0};
        double fWidth{0};
        double fArea{0};
        double fAmplitude{0};
        double fPE{0};
        double fFastToTotal{0};
        OpHit() {}
        virtual ~OpHit() {}
        ClassDef(OpHit, 16);  // Generated by MakeProject.
    };
}  // namespace recob

namespace raw {
    namespace ptb {
        class Trigger {
          public:
            ULong64_t prev_timestamp{0};
            ULong64_t timestamp{0};
            ULong64_t trigger_word{0};
            unsigned int gate_counter{0};
            unsigned int word_type{0};
            Trigger() {}
            virtual ~Trigger() {}
            ClassDef(Trigger, 12);  // Generated by MakeProject.
        };

        class ChStatus {
          public:
            ULong64_t prev_timestamp{0};
            ULong64_t timestamp{0};
            unsigned int beam{0};
            unsigned int crt{0};
            unsigned int pds{0};
            unsigned int mtca{0};
            unsigned int nim{0};
            unsigned int auxpds{0};
            unsigned int word_type{0};
            ChStatus() {}
            virtual ~ChStatus() {}
            ClassDef(ChStatus, 11);  // Generated by MakeProject.
        };

        class Feedback {
          public:
            ULong64_t prev_timestamp{0};
            ULong64_t timestamp{0};
            unsigned int code{0};
            unsigned int source{0};
            unsigned long payload{0};
            unsigned int word_type{0};
            Feedback() {}
            virtual ~Feedback() {}
            ClassDef(Feedback, 11);  // Generated by MakeProject.
        };

        class Misc {
          public:
            ULong64_t prev_timestamp{0};
            ULong64_t timestamp{0};
            ULong64_t payload{0};
            unsigned int word_type{0};
            Misc() {}
            virtual ~Misc() {}
            ClassDef(Misc, 11);  // Generated by MakeProject.
        };

        class WordIndex {
          public:
            unsigned int word_type{0};
            unsigned int index{0};
            WordIndex() {}
            virtual ~WordIndex() {}
            ClassDef(WordIndex, 11);  // Generated by MakeProject.
        };

        class sbndptb {
          public:
            std::vector<Trigger> fHLTriggers;
            std::vector<Trigger> fLLTriggers;
            std::vector<ChStatus> fChStatuses;
            std::vector<Feedback> fFeedbacks;
            std::vector<Misc> fMiscs;
            std::vector<WordIndex> fIndexes;
            sbndptb() {}
            virtual ~sbndptb() {}
            ClassDef(sbndptb, 11);  // Generated by MakeProject.
        };
    }  // namespace ptb
}  // namespace raw

namespace sbnd {
    namespace timing {
        class DAQTimestamp {
          public:
            unsigned int fChannel{0};      // Hardware channel
            unsigned long fTimestamp{0};   // Timestamp of signal [ns]
            unsigned long fOffset{0};      // Channel specific offset [ns]
            std::string fName;             // Name of channel input
            unsigned long fTimestampPs{0}; // Timestamp of signal [ps]
            DAQTimestamp() {}
            virtual ~DAQTimestamp() {}
            ClassDef(DAQTimestamp, 12);  // Generated by MakeProject.
        };

        // From the *_frameshift.root FRAMESHIFT process (sbndcode
        // FrameShift producer); file streamer v10, checksum 0x3cfaed8a.
        class TimingInfo {
          public:
            unsigned long fRawDAQHeaderTimestamp{0};  // event-builder timestamp
            unsigned long fTdcCrtt1{0};     // SPEC-TDC CRT T1 reset [ns]
            unsigned long fTdcBes{0};       // SPEC-TDC BES [ns]
            unsigned long fTdcRwm{0};       // SPEC-TDC RWM [ns]
            unsigned long fTdcEtrig{0};     // SPEC-TDC ETRIG [ns]
            unsigned long fHltCrtt1{0};     // PTB HLT CRT T1 reset [ns]
            unsigned long fHltEtrig{0};     // PTB HLT ETRIG [ns]
            unsigned long fHltBeamGate{0};  // PTB HLT beam gate [ns]
            TimingInfo() {}
            virtual ~TimingInfo() {}
            ClassDef(TimingInfo, 11);
        };

        // File streamer v10, checksum 0x1eb4646b.  fFrameApplyAtCaf is the
        // per-event flash-time correction consumed downstream as the
        // "frame_apply_at_caf" tensor-set metadata (ns).
        class FrameShiftInfo {
          public:
            unsigned short fTimingType{0};  // 0: SPEC TDC ETRIG, 1: HLT ETRIG, 2: none
            double fFrameTdcCrtt1{0};       // decoded frame -> SPEC-TDC CRT T1 [ns]
            double fFrameTdcBes{0};         // decoded frame -> SPEC-TDC BES [ns]
            double fFrameTdcRwm{0};         // decoded frame -> SPEC-TDC RWM [ns]
            double fFrameHltCrtt1{0};       // decoded frame -> HLT CRT T1 [ns]
            double fFrameHltBeamGate{0};    // decoded frame -> HLT beam gate [ns]
            double fFrameApplyAtCaf{0};     // frame to shift to at CAF stage [ns]
            FrameShiftInfo() {}
            virtual ~FrameShiftInfo() {}
            ClassDef(FrameShiftInfo, 11);
        };
    }  // namespace timing
}  // namespace sbnd

namespace artdaq {
    namespace detail {
        class RawEventHeader {
          public:
            unsigned int run_id{0};
            unsigned int subrun_id{0};
            unsigned int event_id{0};
            unsigned long sequence_id{0};
            unsigned long timestamp{0};  // The timestamp of the first Fragment received
            bool is_complete{false};
            unsigned char version{0};
            RawEventHeader() {}
            virtual ~RawEventHeader() {}
        };
    }  // namespace detail
}  // namespace artdaq

namespace art {
    template <int T0> class Hash;
    template <> class Hash<2> {
      public:
        std::string hash_;
        Hash() {}
        virtual ~Hash() {}
        ClassDef(Hash, 11);  // Generated by MakeProject.
    };

    class RunID {
      public:
        unsigned int run_{0};
        RunID() {}
        virtual ~RunID() {}
        ClassDef(RunID, 11);  // Generated by MakeProject.
    };

    class SubRunID {
      public:
        art::RunID run_;
        unsigned int subRun_{0};
        SubRunID() {}
        virtual ~SubRunID() {}
        ClassDef(SubRunID, 11);  // Generated by MakeProject.
    };

    class EventID {
      public:
        art::SubRunID subRun_;
        unsigned int event_{0};
        EventID() {}
        virtual ~EventID() {}
        ClassDef(EventID, 13);  // Generated by MakeProject.
    };

    class Timestamp {
      public:
        unsigned int timeLow_{0};   // nanoseconds
        unsigned int timeHigh_{0};  // seconds since epoch
        Timestamp() {}
        virtual ~Timestamp() {}
        ClassDef(Timestamp, 11);  // Generated by MakeProject.
    };

    class EventAuxiliary {
      public:
        enum ExperimentType { kDefault_ExperimentType };
        art::Hash<2> processHistoryID_;
        art::EventID id_;
        art::Timestamp time_;
        bool isRealData_{false};
        Int_t experimentType_{0};
        EventAuxiliary() {}
        virtual ~EventAuxiliary() {}
        ClassDef(EventAuxiliary, 13);  // Generated by MakeProject.
    };

    class RunAuxiliary {
      public:
        art::Hash<2> processHistoryID_;
        unsigned int rangeSetID_{0};
        art::RunID id_;
        art::Timestamp beginTime_;
        art::Timestamp endTime_;
        RunAuxiliary() {}
        virtual ~RunAuxiliary() {}
        ClassDef(RunAuxiliary, 13);  // Generated by MakeProject.
    };

    class EDProduct {
      public:
        EDProduct() {}
        virtual ~EDProduct() {}
        ClassDef(EDProduct, 11);  // Generated by MakeProject.
    };

    template <typename T0> class Wrapper;

    template <> class Wrapper<std::vector<recob::Wire> > : public art::EDProduct {
      public:
        bool present{false};
        unsigned int rangeSetID{0};
        std::vector<recob::Wire> obj;
        Wrapper() {}
        virtual ~Wrapper() {}
        ClassDef(Wrapper, 12);  // Generated by MakeProject.
    };

    template <> class Wrapper<std::vector<recob::OpFlash> > : public art::EDProduct {
      public:
        bool present{false};
        unsigned int rangeSetID{0};
        std::vector<recob::OpFlash> obj;
        Wrapper() {}
        virtual ~Wrapper() {}
        ClassDef(Wrapper, 12);  // Generated by MakeProject.
    };

    template <> class Wrapper<std::vector<recob::OpHit> > : public art::EDProduct {
      public:
        bool present{false};
        unsigned int rangeSetID{0};
        std::vector<recob::OpHit> obj;
        Wrapper() {}
        virtual ~Wrapper() {}
        ClassDef(Wrapper, 12);  // Generated by MakeProject.
    };

    template <> class Wrapper<std::vector<int> > : public art::EDProduct {
      public:
        bool present{false};
        unsigned int rangeSetID{0};
        std::vector<int> obj;
        Wrapper() {}
        virtual ~Wrapper() {}
        ClassDef(Wrapper, 12);  // Generated by MakeProject.
    };

    template <> class Wrapper<std::vector<double> > : public art::EDProduct {
      public:
        bool present{false};
        unsigned int rangeSetID{0};
        std::vector<double> obj;
        Wrapper() {}
        virtual ~Wrapper() {}
        ClassDef(Wrapper, 12);  // Generated by MakeProject.
    };

    template <> class Wrapper<std::vector<raw::ptb::sbndptb> > : public art::EDProduct {
      public:
        bool present{false};
        unsigned int rangeSetID{0};
        std::vector<raw::ptb::sbndptb> obj;
        Wrapper() {}
        virtual ~Wrapper() {}
        ClassDef(Wrapper, 12);  // Generated by MakeProject.
    };

    template <> class Wrapper<std::vector<sbnd::timing::DAQTimestamp> > : public art::EDProduct {
      public:
        bool present{false};
        unsigned int rangeSetID{0};
        std::vector<sbnd::timing::DAQTimestamp> obj;
        Wrapper() {}
        virtual ~Wrapper() {}
        ClassDef(Wrapper, 12);  // Generated by MakeProject.
    };

    template <> class Wrapper<artdaq::detail::RawEventHeader> : public art::EDProduct {
      public:
        bool present{false};
        unsigned int rangeSetID{0};
        artdaq::detail::RawEventHeader obj;
        Wrapper() {}
        virtual ~Wrapper() {}
        ClassDef(Wrapper, 12);  // Generated by MakeProject.
    };

    template <> class Wrapper<sbnd::timing::TimingInfo> : public art::EDProduct {
      public:
        bool present{false};
        unsigned int rangeSetID{0};
        sbnd::timing::TimingInfo obj;
        Wrapper() {}
        virtual ~Wrapper() {}
        ClassDef(Wrapper, 12);
    };

    template <> class Wrapper<sbnd::timing::FrameShiftInfo> : public art::EDProduct {
      public:
        bool present{false};
        unsigned int rangeSetID{0};
        sbnd::timing::FrameShiftInfo obj;
        Wrapper() {}
        virtual ~Wrapper() {}
        ClassDef(Wrapper, 12);
    };
}  // namespace art

#endif
