#!/bin/bash
mydir=$(dirname $(realpath $BASH_SOURCE))

prog=afvslt
export TDIR=$PREFIX/lib/python3.11/site-packages/torch

# can not get OpenCL/PoCL/ocl-icd/etc/etc/ to work
# openclflags=$(pkg-config --libs --cflags OpenCL)
# poclflags=$(pkg-config --libs --cflags pocl)

set -x
g++ -O2 -std=c++20 -ggdb3 \
    -o $prog $mydir/${prog}.cpp \
    -isystem $PREFIX/include \
    -isystem PREFIX/targets/x86_64-linux/include \
    -isystem $TDIR/include \
    -isystem $TDIR/include/torch/csrc/api/include \
    -isystem $PREFIX/include/eigen3 \
    -L $PREFIX/lib \
    -L $PREFIX/targets/x86_64-linux/lib \
    -L $TDIR/lib \
    -laf \
    -ltorch -ltorch_cpu -lc10 -lc10_cuda -ltorch_cuda \
    -Wl,--no-as-needed,"$TDIR/lib/libtorch.so" \
    -Wl,--no-as-needed,"$TDIR/lib/libtorch_cpu.so" \
    -Wl,--no-as-needed,"$TDIR/lib/libtorch_cuda.so" \
    -lcudart -lcuda \
    $openclflags \
    $poclflags \
    -lfftw3f \
    -Wl,-rpath,$PREFIX/lib:$PREFIX/targets/x86_64-linux/lib:$TDIR/lib || exit 1

